#!/usr/bin/env bash
# Local release builder — produces signed iOS .ipa + macOS .pkg.
#
# Called by fastlane/Fastfile's `release` lane. Usage:
#   ci/local-release-check.sh v0.1.0 --sign-ios --sign-macos
#   ci/local-release-check.sh v0.1.0 --sign-ios               # iOS only
#   ci/local-release-check.sh v0.1.0 --sign-macos             # macOS only
#   ci/local-release-check.sh v0.1.0 --sign                   # both
#
# Output (created if missing):
#   build/HelloApp-<version>.ipa
#   build/HelloApp-<version>.pkg
#
# Reads .env.local for:
#   FASTLANE_TEAM_ID  (or APPLE_TEAM_ID as a fallback name)
#
# Distribution cert + Mac Installer Distribution cert must be in the login
# Keychain. Provisioning profiles are auto-generated by `-allowProvisioningUpdates`
# during archive.
#
# Includes the macOS app-sandbox re-sign hack: Xcode's auto-managed Mac App
# Store profile strips com.apple.security.app-sandbox; TestFlight rejects
# sandbox-less .pkgs with ITMS-90296. We expand the .pkg, force-add sandbox
# entitlements, repack.

set -euo pipefail

# ── Args ──────────────────────────────────────────────────────────────────────

if [ "${1:-}" = "--help" ] || [ -z "${1:-}" ]; then
  sed -n '2,/^set -e/p' "$0" | sed 's/^# \{0,2\}//' | sed '$d'
  exit 0
fi

TAG="${1}"
SIGN_IOS=false
SIGN_MACOS=false

for arg in "${@:2}"; do
  case $arg in
    --sign-ios)   SIGN_IOS=true ;;
    --sign-macos) SIGN_MACOS=true ;;
    --sign)       SIGN_IOS=true; SIGN_MACOS=true ;;
  esac
done

# ── Setup ─────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [ -f .env.local ]; then
  # shellcheck disable=SC1091
  source .env.local
fi

TEAM_ID="${FASTLANE_TEAM_ID:-${APPLE_TEAM_ID:-}}"
if [ -z "$TEAM_ID" ] && { $SIGN_IOS || $SIGN_MACOS; }; then
  echo "FAIL: FASTLANE_TEAM_ID (or APPLE_TEAM_ID) not set in .env.local" >&2
  exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

if command -v xcbeautify >/dev/null 2>&1; then
  XCBEAUTIFY=( xcbeautify --renderer terminal )
else
  XCBEAUTIFY=( cat )
fi

step() { printf '\n==> %s\n' "$*"; }
ok()   { printf '    ✓ %s\n' "$*"; }
fail() { printf '    ✗ %s\n' "$*" >&2; exit 1; }

# Apple Distribution cert SHA-1 resolver — shared library across indiagrams projects.
. "$(dirname "${BASH_SOURCE[0]}")/lib/resolve-dist-cert-sha.sh"

VERSION="${TAG#v}"
MARKETING_VERSION="${RELEASE_MARKETING_VERSION:-${VERSION%%-*}}"

# ── Tag format check ──────────────────────────────────────────────────────────

step "Tag format"
if echo "$TAG" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+([-+].+)?$'; then
  ok "$TAG"
else
  fail "Tag '$TAG' does not match v[0-9]+.[0-9]+.[0-9]+(...) (e.g. v0.1.0, v0.1.0-rc1)"
fi

# ── Regenerate xcodeproj + Generated-Info.plist ───────────────────────────────

step "xcodegen generate"
( cd app && xcodegen generate >/dev/null )
ok "HelloApp.xcodeproj regenerated"

mkdir -p "$REPO_ROOT/build"

# ─────────────────────────────────────────────────────────────────────────────
# iOS archive + IPA export
# ─────────────────────────────────────────────────────────────────────────────

if $SIGN_IOS; then
  step "iOS archive (signed)"

  IOS_ARCHIVE="$WORK_DIR/HelloApp-iOS.xcarchive"
  IOS_EXPORT="$WORK_DIR/export-ios"
  EXPORT_OPTS="$WORK_DIR/ExportOptions-iOS.plist"

  cp ci/ExportOptions-iOS.plist "$EXPORT_OPTS"
  sed -i '' "s/TEAM_ID_PLACEHOLDER/$TEAM_ID/g" "$EXPORT_OPTS"

  xcodebuild archive \
    -project app/HelloApp.xcodeproj \
    -scheme HelloApp-iOS \
    -configuration Release \
    -destination 'generic/platform=iOS' \
    -archivePath "$IOS_ARCHIVE" \
    -allowProvisioningUpdates \
    DEVELOPMENT_TEAM="$TEAM_ID" \
    MARKETING_VERSION="$MARKETING_VERSION" \
    CURRENT_PROJECT_VERSION="0" \
    2>&1 | "${XCBEAUTIFY[@]}"

  step "iOS export (App Store)"
  xcodebuild -exportArchive \
    -archivePath "$IOS_ARCHIVE" \
    -exportOptionsPlist "$EXPORT_OPTS" \
    -exportPath "$IOS_EXPORT" \
    -allowProvisioningUpdates \
    2>&1 | "${XCBEAUTIFY[@]}"

  IPA_SRC=$(find "$IOS_EXPORT" -maxdepth 2 -name "*.ipa" | head -1)
  [ -z "$IPA_SRC" ] && fail "exportArchive produced no .ipa in $IOS_EXPORT"

  IPA_DEST="$REPO_ROOT/build/HelloApp-${VERSION}.ipa"
  cp "$IPA_SRC" "$IPA_DEST"
  shasum -a 256 "$IPA_DEST" > "$IPA_DEST.sha256"
  ok "$IPA_DEST"
  ok "$(cat "$IPA_DEST.sha256")"
fi

# ─────────────────────────────────────────────────────────────────────────────
# macOS archive + .pkg export (with app-sandbox re-sign)
# ─────────────────────────────────────────────────────────────────────────────

if $SIGN_MACOS; then
  step "macOS archive (signed)"

  MACOS_ARCHIVE="$WORK_DIR/HelloApp-macOS.xcarchive"
  MACOS_EXPORT="$WORK_DIR/export-macos"
  EXPORT_OPTS_MACOS="$WORK_DIR/ExportOptions-macOS-AppStore.plist"

  cp ci/ExportOptions-macOS-AppStore.plist "$EXPORT_OPTS_MACOS"
  sed -i '' "s/TEAM_ID_PLACEHOLDER/$TEAM_ID/g" "$EXPORT_OPTS_MACOS"

  xcodebuild archive \
    -project app/HelloApp.xcodeproj \
    -scheme HelloApp-macOS \
    -configuration Release \
    -destination 'generic/platform=macOS' \
    -archivePath "$MACOS_ARCHIVE" \
    -allowProvisioningUpdates \
    CODE_SIGN_STYLE=Automatic \
    DEVELOPMENT_TEAM="$TEAM_ID" \
    MARKETING_VERSION="$MARKETING_VERSION" \
    CURRENT_PROJECT_VERSION="0" \
    2>&1 | "${XCBEAUTIFY[@]}"

  step "macOS export"
  xcodebuild -exportArchive \
    -archivePath "$MACOS_ARCHIVE" \
    -exportPath "$MACOS_EXPORT" \
    -exportOptionsPlist "$EXPORT_OPTS_MACOS" \
    -allowProvisioningUpdates \
    2>&1 | "${XCBEAUTIFY[@]}"

  EXPORTED_PKG=$(find "$MACOS_EXPORT" -maxdepth 2 -name "*.pkg" | head -1)
  [ -z "$EXPORTED_PKG" ] && fail "exportArchive produced no .pkg in $MACOS_EXPORT"

  # ─── app-sandbox re-sign hack ──────────────────────────────────────────────
  # Xcode's auto-managed Mac App Store profile doesn't list app-sandbox as a
  # capability, so the signed .app strips com.apple.security.app-sandbox. TestFlight
  # rejects with ITMS-90296. We expand the .pkg, force-add sandbox entitlements
  # back into the .app's signature, and repack.
  step "macOS: re-sign with app-sandbox entitlements"

  PKG_EXPANDED="$WORK_DIR/pkg-expanded"
  pkgutil --expand-full "$EXPORTED_PKG" "$PKG_EXPANDED"
  EXPANDED_APP=$(find "$PKG_EXPANDED" -maxdepth 5 -name "*.app" | head -1)
  [ -z "$EXPANDED_APP" ] && fail "pkgutil --expand-full produced no .app"

  # Pin to the cert SHA-1 from the .app's embedded provisioning profile.
  APPLE_DIST_SHA=$(resolve_dist_cert_sha_from_app "$EXPANDED_APP") \
    || fail "Could not resolve cert SHA-1 from $EXPANDED_APP/Contents/embedded.provisionprofile"
  ok "Using Apple Distribution cert: $APPLE_DIST_SHA (from embedded profile)"

  # Re-sign nested frameworks/dylibs first (codesign hashes them inside-out).
  while IFS= read -r nested; do
    codesign --force --sign "$APPLE_DIST_SHA" --timestamp "$nested" 2>/dev/null || true
  done < <(find "$EXPANDED_APP/Contents/Frameworks" \( -name "*.framework" -o -name "*.dylib" \) 2>/dev/null)

  # Extract Xcode's embedded entitlements (with team-managed identifiers) and
  # merge sandbox on top. Static entitlements would lose application-identifier /
  # team-identifier and trigger error 90886.
  #
  # PlistBuddy's `Set` does NOT accept a type keyword — `Set :key bool true`
  # silently discards the `bool` arg. Use `Set :key true` (existing keys) +
  # `Add :key bool true` (new keys).
  MERGED_ENTITLEMENTS="$WORK_DIR/merged-entitlements.plist"
  codesign -d --entitlements :"$MERGED_ENTITLEMENTS" "$EXPANDED_APP"
  _set() {
    /usr/libexec/PlistBuddy -c "Set :$1 $2" "$MERGED_ENTITLEMENTS" 2>/dev/null \
      || /usr/libexec/PlistBuddy -c "Add :$1 bool $2" "$MERGED_ENTITLEMENTS"
  }
  _set com.apple.security.app-sandbox     true
  # Add others as your app needs them. Common extras:
  #   _set com.apple.security.network.client  true
  #   _set com.apple.security.network.server  true
  #   _set com.apple.security.device.camera   true

  codesign --force --sign "$APPLE_DIST_SHA" \
    --entitlements "$MERGED_ENTITLEMENTS" \
    --timestamp \
    "$EXPANDED_APP"

  step "macOS: productbuild"
  INSTALLER_CERT=$(security find-identity -v -p basic 2>/dev/null \
    | grep -E "3rd Party Mac Developer Installer|Mac Installer Distribution" \
    | head -1 | grep -oE '"[^"]+"' | tr -d '"')
  [ -z "$INSTALLER_CERT" ] && fail "Mac Installer Distribution cert not found in keychain — install one from developer.apple.com → Certificates → '+' → Mac Installer Distribution"

  PKG_DEST="$REPO_ROOT/build/HelloApp-${VERSION}.pkg"
  productbuild --component "$EXPANDED_APP" /Applications \
    --sign "$INSTALLER_CERT" \
    --timestamp \
    "$PKG_DEST"
  shasum -a 256 "$PKG_DEST" > "$PKG_DEST.sha256"
  ok "$PKG_DEST"
  ok "$(cat "$PKG_DEST.sha256")"
fi

echo
echo "✓ Release artifacts ready for $TAG"
$SIGN_IOS   && echo "    iOS:   build/HelloApp-${VERSION}.ipa"
$SIGN_MACOS && echo "    macOS: build/HelloApp-${VERSION}.pkg"
echo
echo "Next: fastlane release uploads via pilot, then pushes the tag."
